name: docs
"on":
  push:
    branches:
      - main
  workflow_dispatch: null
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
jobs:
  build:
    name: build / stable
    env:
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Install nightly Rust toolchain
        uses: dtolnay/rust-toolchain@b44cb146d03e8d870c57ab64b80f04586349ca5d
        with:
          toolchain: nightly
      - name: Build docs
        env:
          RUSTDOCFLAGS: --enable-index-page -Z unstable-options
        run: cargo doc --no-deps
      - name: Upload github-pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc
  deploy:
    name: deploy / github-pages
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
