name: flush cache

on:
  # Allow manually running this workflow.
  workflow_dispatch:

jobs:
  flush_cache:
    name: flush cache
    permissions:
      actions: write
    uses: EarthmanMuons/reusable-workflows/.github/workflows/flush-cache.yml@main
