name: preload cache

on:
  push:
    branches:
      - main
    paths:
      - "**/Cargo.*"
      - .github/workflows/*.yml

  schedule:
    # Run every Monday at 7:45am UTC.
    - cron: 45 7 * * 1

  # Allow manually running this workflow.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cache_actionlint:
    name: cache actionlint
    uses: EarthmanMuons/reusable-workflows/.github/workflows/preload-cache-actionlint.yml@main

  cache_rust:
    name: cache rust
    uses: EarthmanMuons/reusable-workflows/.github/workflows/preload-cache-rust.yml@main
