name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - staging
      - trying

env:
  CARGO_TERM_COLOR: always

jobs:
  required:
    name: ubuntu / stable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile tests
        run: cargo test --locked --no-run
      - name: Run tests
        run: cargo test --locked

  workflow_status:
    name: test workflow status
    if: always()
    runs-on: ubuntu-latest
    needs:
      - required
    steps:
      - name: Check `ubuntu / stable` job status
        run: |
          [[ "${{ needs.required.result }}" = "success" ]] && exit 0 || exit 1
