name: test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - staging
      - trying

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  CI: 1
  RUSTFLAGS: "-D warnings"

jobs:
  required:
    name: ubuntu / stable
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Compile tests
        run: cargo test --locked --no-run

      - name: Run tests
        run: cargo test --locked

  workflow_status:
    name: test workflow status
    if: always()
    runs-on: ubuntu-latest
    needs:
      - required
    steps:
      - name: Check `ubuntu / stable` job status
        run: |
          [[ "${{ needs.required.result }}" = "success" ]] && exit 0 || exit 1
